"use client";

import { type FormEvent, useCallback, useEffect, useRef, useState } from "react";
import { EmptyState, ErrorState, LoadingState } from "@/components/ui/async-state";
import { PageHeader } from "@/components/ui/page-header";
import { adminApi } from "@/lib/api/admin-api";
import type { AdminDepartment } from "@/lib/api/admin-types";

export function DepartmentManagement() {
  const [items, setItems] = useState<AdminDepartment[]>([]); const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [editingId, setEditingId] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const busy = useRef(false);
  const load = useCallback(async () => { try { setItems(await adminApi.getDepartments()); setError(null); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to load departments."); } finally { setLoading(false); } }, []);
  useEffect(() => { let active = true; adminApi.getDepartments().then((value) => { if (active) setItems(value); }).catch((caught: unknown) => { if (active) setError(caught instanceof Error ? caught.message : "Unable to load departments."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  function resetForm() { setEditingId(null); setName(""); setDescription(""); }
  function edit(item: AdminDepartment) { setEditingId(item.id); setName(item.name); setDescription(item.description ?? ""); }
  async function save(event: FormEvent) { event.preventDefault(); if (busy.current) return; busy.current = true; try { const input = { name: name.trim(), description: description.trim() || null }; if (editingId) await adminApi.updateDepartment(editingId, input); else await adminApi.createDepartment(input); resetForm(); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to save department."); } finally { busy.current = false; } }
  async function toggle(item: AdminDepartment) { try { await adminApi.updateDepartment(item.id, { isActive: !item.isActive }); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to update department."); } }
  return <div className="page-stack"><PageHeader eyebrow="Organization structure" title="Departments" description="Maintain unique departments without silently moving employees or rewriting history." /><form className="card admin-inline-form" onSubmit={save}><div className="field-group"><label htmlFor="department-name">Department name</label><input id="department-name" value={name} minLength={2} onChange={(event) => setName(event.target.value)} required /></div><div className="field-group"><label htmlFor="department-description">Description</label><input id="department-description" value={description} onChange={(event) => setDescription(event.target.value)} /></div><button className="button button-primary" type="submit">{editingId ? "Save changes" : "Add department"}</button>{editingId ? <button className="button button-secondary" type="button" onClick={resetForm}>Cancel</button> : null}</form>{loading ? <LoadingState label="Loading departments…" /> : error && !items.length ? <ErrorState message={error} onRetry={load} /> : !items.length ? <EmptyState title="No departments" message="Create the first organization department." /> : <section className="card data-table-wrap">{error ? <p className="form-error" role="alert">{error}</p> : null}<table className="data-table"><thead><tr><th>Name</th><th>Description</th><th>Employees</th><th>Status</th><th>Actions</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><strong>{item.name}</strong></td><td>{item.description ?? "—"}</td><td>{item._count.users}</td><td>{item.isActive ? "Active" : "Inactive"}</td><td><div className="button-row"><button className="button button-secondary" onClick={() => edit(item)} type="button">Edit</button><button className="button button-secondary" onClick={() => void toggle(item)} type="button">{item.isActive ? "Deactivate" : "Activate"}</button></div></td></tr>)}</tbody></table></section>}</div>;
}
