"use client";

import { useRouter } from "next/navigation";
import { type FormEvent, useEffect, useRef, useState } from "react";

import { ErrorState, LoadingState } from "@/components/ui/async-state";
import { PageHeader } from "@/components/ui/page-header";
import type { UserRole } from "@/generated/prisma/enums";
import { adminApi } from "@/lib/api/admin-api";
import type { AdminDepartment, AdminEmployee, EmployeePayload } from "@/lib/api/admin-types";

export function EmployeeForm({ employeeId }: { employeeId?: string }) {
  const router = useRouter(); const submittingRef = useRef(false); const [departments, setDepartments] = useState<AdminDepartment[]>([]); const [managers, setManagers] = useState<AdminEmployee[]>([]); const [originalRole, setOriginalRole] = useState<UserRole | null>(null); const [loading, setLoading] = useState(Boolean(employeeId)); const [error, setError] = useState<string | null>(null); const [submitting, setSubmitting] = useState(false); const [values, setValues] = useState<EmployeePayload>({ email: "", name: "", role: "EMPLOYEE", departmentId: null, managerId: null, isActive: true });
  useEffect(() => { let active = true; Promise.all([adminApi.getDepartments(), adminApi.getEmployees({ page: 1, pageSize: 100, role: "MANAGER", isActive: "true" }), employeeId ? adminApi.getEmployee(employeeId) : Promise.resolve(null)]).then(([departmentData, managerData, employee]) => { if (!active) return; setDepartments(departmentData.filter((item) => item.isActive)); setManagers(managerData.data); if (employee) { setOriginalRole(employee.role); setValues({ email: employee.email, name: employee.name, role: employee.role, departmentId: employee.departmentId, managerId: employee.managerId, isActive: employee.isActive }); } }).catch((caught: unknown) => { if (active) setError(caught instanceof Error ? caught.message : "Unable to load employee form."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [employeeId]);
  function set<K extends keyof EmployeePayload>(key: K, value: EmployeePayload[K]) { setValues((current) => ({ ...current, [key]: value })); setError(null); }
  async function submit(event: FormEvent) { event.preventDefault(); if (submittingRef.current) return; if (values.name.trim().length < 2) { setError("Enter the employee’s full name."); return; } if (!employeeId && !values.email.includes("@")) { setError("Enter a valid email address."); return; } if (values.managerId && values.managerId === employeeId) { setError("An employee cannot manage themselves."); return; } submittingRef.current = true; setSubmitting(true); try { const employee = employeeId ? await adminApi.updateEmployee(employeeId, { name: values.name.trim(), role: values.role, departmentId: values.departmentId, managerId: values.managerId, isActive: values.isActive }) : await adminApi.createEmployee({ ...values, name: values.name.trim(), email: values.email.trim().toLowerCase() }); router.replace(`/admin/employees/${employee.id}`); router.refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to save employee."); } finally { submittingRef.current = false; setSubmitting(false); } }
  if (loading) return <LoadingState label="Loading employee form…" />; if (error && !departments.length && employeeId) return <ErrorState message={error} />;
  const privilegeChange = Boolean(employeeId && originalRole && originalRole !== values.role);
  return <div className="form-page"><PageHeader eyebrow="Employee management" title={employeeId ? "Edit employee" : "Create employee"} description={employeeId ? "Changes take effect on the employee’s next authorization check." : "An invitation will be sent through Supabase Auth; no reusable password is created or displayed."} /><form className="card leave-form" onSubmit={submit} noValidate><div className="field-group"><label htmlFor="admin-name">Full name</label><input id="admin-name" value={values.name} onChange={(event) => set("name", event.target.value)} required /></div><div className="field-group"><label htmlFor="admin-email">Email</label><input id="admin-email" type="email" value={values.email} onChange={(event) => set("email", event.target.value)} disabled={Boolean(employeeId)} required /></div><div className="date-grid"><div className="field-group"><label htmlFor="admin-role">Role</label><select id="admin-role" value={values.role} onChange={(event) => set("role", event.target.value as UserRole)}>{["EMPLOYEE","MANAGER","HR","ADMIN"].map((role) => <option key={role}>{role}</option>)}</select></div><div className="field-group"><label htmlFor="admin-department">Department</label><select id="admin-department" value={values.departmentId ?? ""} onChange={(event) => { set("departmentId", event.target.value || null); set("managerId", null); }}><option value="">Unassigned</option>{departments.map((department) => <option value={department.id} key={department.id}>{department.name}</option>)}</select></div></div><div className="field-group"><label htmlFor="admin-manager">Manager</label><select id="admin-manager" value={values.managerId ?? ""} onChange={(event) => set("managerId", event.target.value || null)}><option value="">No manager</option>{managers.filter((manager) => manager.id !== employeeId && manager.departmentId === values.departmentId).map((manager) => <option value={manager.id} key={manager.id}>{manager.name}</option>)}</select><small>Managers must be active and in the same department.</small></div><label className="checkbox-field"><input type="checkbox" checked={values.isActive} onChange={(event) => set("isActive", event.target.checked)} /><span>Account is active</span></label>{privilegeChange ? <p className="warning-callout" role="alert">Changing roles immediately changes authorization on subsequent server requests.</p> : null}{error ? <p className="form-error" role="alert">{error}</p> : null}<div className="form-actions"><button className="button button-secondary" type="button" onClick={() => router.back()}>Cancel</button><button className="button button-primary" disabled={submitting} type="submit">{submitting ? "Saving…" : employeeId ? "Save changes" : "Send invitation"}</button></div></form></div>;
}
