"use client";

import { type FormEvent, useCallback, useEffect, useRef, useState } from "react";
import { EmptyState, ErrorState, LoadingState } from "@/components/ui/async-state";
import { PageHeader } from "@/components/ui/page-header";
import { adminApi } from "@/lib/api/admin-api";
import type { AdminLeaveType } from "@/lib/api/admin-types";

export function LeaveTypeManagement() {
  const [items, setItems] = useState<AdminLeaveType[]>([]); const [code, setCode] = useState(""); const [name, setName] = useState(""); const [isPaid, setIsPaid] = useState(true); const [editingId, setEditingId] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const busy = useRef(false);
  const load = useCallback(async () => { try { setItems(await adminApi.getLeaveTypes()); setError(null); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to load leave types."); } finally { setLoading(false); } }, []); useEffect(() => { let active = true; adminApi.getLeaveTypes().then((value) => { if (active) setItems(value); }).catch((caught: unknown) => { if (active) setError(caught instanceof Error ? caught.message : "Unable to load leave types."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  function resetForm() { setEditingId(null); setCode(""); setName(""); setIsPaid(true); }
  function edit(item: AdminLeaveType) { setEditingId(item.id); setCode(item.code); setName(item.name); setIsPaid(item.isPaid); }
  async function save(event: FormEvent) { event.preventDefault(); if (busy.current) return; busy.current = true; try { if (editingId) await adminApi.updateLeaveType(editingId, { name: name.trim(), isPaid }); else await adminApi.createLeaveType({ code: code.trim().toUpperCase(), name: name.trim(), isPaid, isActive: true }); resetForm(); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to save leave type."); } finally { busy.current = false; } }
  async function toggle(item: AdminLeaveType) { try { await adminApi.updateLeaveType(item.id, { isActive: !item.isActive }); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to update leave type."); } }
  return <div className="page-stack"><PageHeader eyebrow="Leave configuration" title="Leave types" description="Codes remain stable after creation; referenced records are deactivated rather than deleted." /><form className="card admin-inline-form" onSubmit={save}><div className="field-group"><label htmlFor="type-code">Stable code</label><input id="type-code" value={code} onChange={(event) => setCode(event.target.value)} placeholder="PARENTAL" disabled={Boolean(editingId)} required /></div><div className="field-group"><label htmlFor="type-name">Display name</label><input id="type-name" value={name} onChange={(event) => setName(event.target.value)} required /></div><label className="checkbox-field"><input type="checkbox" checked={isPaid} onChange={(event) => setIsPaid(event.target.checked)} /> Paid leave</label><button className="button button-primary">{editingId ? "Save changes" : "Add leave type"}</button>{editingId ? <button className="button button-secondary" type="button" onClick={resetForm}>Cancel</button> : null}</form>{loading ? <LoadingState label="Loading leave types…" /> : error && !items.length ? <ErrorState message={error} /> : !items.length ? <EmptyState title="No leave types" message="Create the first leave type." /> : <section className="card data-table-wrap">{error ? <p className="form-error">{error}</p> : null}<table className="data-table"><thead><tr><th>Code</th><th>Name</th><th>Payment</th><th>Policies</th><th>Balances</th><th>Status</th><th>Actions</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><strong>{item.code}</strong></td><td>{item.name}</td><td>{item.isPaid ? "Paid" : "Unpaid"}</td><td>{item._count.policies}</td><td>{item._count.balances}</td><td>{item.isActive ? "Active" : "Inactive"}</td><td><div className="button-row"><button className="button button-secondary" type="button" onClick={() => edit(item)}>Edit</button><button className="button button-secondary" type="button" onClick={() => void toggle(item)}>{item.isActive ? "Deactivate" : "Activate"}</button></div></td></tr>)}</tbody></table></section>}</div>;
}
